#ifndef ENUMS_H
#define ENUMS_H


enum class FUEL_TYPE { PETROL, DIESEL, PROPANE_BUTANE, METHANE, ELECTRICITY };


enum class CONSUMPTION_NAME { SERVICE, REFUELING, OTHER_CONSUMPTION };


enum class SERVICE_NAME { MAINTENANCE, REPAIR, TUNING, DETAIL, DIAGNOSTICS, TIRE_FITTING, OTHER_SERVICE };


#endif // ENUMS_H
